---
name: Catalyst-Plugin-Browser
version: 0.02
author:
  - |-
    Christian Hansen, C<ch@ngmedia.com>
    Marcus Ramberg, C<mramberg@cpan.org>
abstract: Browser Detection
license: perl
requires:
  HTTP::BrowserDetect: 0
provides:
  Catalyst::Plugin::Browser:
    file: lib/Catalyst/Plugin/Browser.pm
    version: 0.02
  Catalyst::Request:
    file: lib/Catalyst/Plugin/Browser.pm
    version: 0.02
generated_by: Module::Build version 0.26
