# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-XMLRPC
version:      0.10
version_from: lib/Catalyst/Plugin/XMLRPC.pm
installdirs:  site
requires:
    Catalyst:                      5.66
    RPC::XML:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
