# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Pluggable-Fast
version:      0.16
version_from: Fast.pm
installdirs:  site
requires:
    File::Find:                    0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
