---
name: DBIx-Migration
version: 0.04
author:
  - 'Sebastian Riedel, C<sri@oook.de>'
abstract: 'Seamless DB schema up- and downgrades'
license: perl
requires:
  Class::Accessor::Fast: 0
  DBI: 0
  File::Slurp: 0
  File::Spec: 0
provides:
  DBIx::Migration:
    file: lib/DBIx/Migration.pm
    version: 0.04
generated_by: Module::Build version 0.2611
