# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Authentication-LDAP
version:      0.01
version_from: LDAP.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Catalyst::Plugin::Session::FastMmap: 0
    Net::LDAP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
