---
name: Catalyst-Plugin-Unicode
version: 0.2
author:
  - |-
    Christian Hansen, C<ch@ngmedia.com>
    Marcus Ramberg, C<mramberg@pcan.org>
abstract: Unicode aware Catalyst
license: perl
provides:
  Catalyst::Plugin::Unicode:
    file: lib/Catalyst/Plugin/Unicode.pm
    version: 0.2
generated_by: Module::Build version 0.26
