---
name: Catalyst-Log-Dispatch
version: 0.1
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Log::Dispatch
license: perl
requires:
  Catalyst: 5.23
  Log::Dispatch: 0
provides:
  Catalyst::Log::Dispatch:
    file: lib/Catalyst/Log/Dispatch.pm
    version: 0.1
generated_by: Module::Build version 0.2608
