---
name: Catalyst-Plugin-Compress-Zlib
version: 0.01
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Zlib Compression for Catalyst
license: perl
requires:
  Compress::Zlib: 0
provides:
  Catalyst::Plugin::Compress::Deflate:
    file: lib/Catalyst/Plugin/Compress/Deflate.pm
  Catalyst::Plugin::Compress::Gzip:
    file: lib/Catalyst/Plugin/Compress/Gzip.pm
  Catalyst::Plugin::Compress::Zlib:
    file: lib/Catalyst/Plugin/Compress/Zlib.pm
    version: 0.01
generated_by: Module::Build version 0.2609
