---
name: Catalyst-Plugin-Singleton
version: 0.02
author:
  - Christian Hansen, C<ch@ngmedia.com>
abstract: Singleton to context
license: perl
requires:
  Scalar::Util: 0
provides:
  Catalyst::Plugin::Singleton:
    file: lib/Catalyst/Plugin/Singleton.pm
    version: 0.02
generated_by: Module::Build version 0.26
