use strict;
use Module::Build;

my $build = Module::Build->new(
    create_makefile_pl => 'traditional',
    license            => 'perl',
    module_name        => 'Catalyst::Plugin::Session::Store::Memcached',
    requires           => {
        'Catalyst::Plugin::Session' => 0.01,
        'Cache::Memcached::Managed' => 0,
    },
    create_readme => 1,
    sign          => 1,
);
$build->create_build_script;

