# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-CDBI
version:      0.11
version_from: lib/Catalyst/Model/CDBI.pm
installdirs:  site
requires:
    Catalyst:                      4.00
    Class::DBI:                    0
    Class::DBI::Loader:            0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
