--- #YAML:1.0
name: HTML-Prototype
version: 1.36
author:
  - Sascha Kiefer, C<esskar@cpan.org>
Sebastian Riedel, C<sri@oook.de>
Marcus Ramberg, C<mramberg@cpan.org>
abstract: Generate HTML and Javascript for the Prototype library
license: perl
generated_by: Module::Build version 0.2609, without YAML.pm
