---
name: Catalyst-Model-SPOPS
version: 0.01
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: SPOPS Model Class
license: perl
requires:
  Catalyst: 5.2
  SPOPS: 0.87
provides:
  Catalyst::Model::SPOPS:
    file: lib/Catalyst/Model/SPOPS.pm
    version: 0.01
generated_by: Module::Build version 0.2608
