# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-Proxy
version:      0.02
version_from: lib/Catalyst/Model/Proxy.pm
installdirs:  site
requires:
    Catalyst:                      5.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
