---
name: Catalyst-Model-Search
version: 0.01
author: ~
abstract: ~
license: perl
requires:
  Catalyst: 5.33
recommends:
  Plucene: 0
provides:
  Catalyst::Model::Search:
    file: lib/Catalyst/Model/Search.pm
    version: 0.01
  Catalyst::Model::Search::Plucene:
    file: lib/Catalyst/Model/Search/Plucene.pm
    version: 0.01
generated_by: Module::Build version 0.2611
