package JQChatDB;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships => 1,
    # debug => 1,
);

=head1 NAME

JQChatDB - DBIx::Class::Schema::Loader class

=head1 SYNOPSIS

See L<JQChat>

=head1 DESCRIPTION

Generated by L<Catalyst::Model::DBIC::Schema> for use in L<JQChat::Model::JQChatDB>

=head1 AUTHOR

Kieren Diment

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

