# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Log-Log4perl
version:      0.1
version_from: lib/Catalyst/Log/Log4perl.pm
installdirs:  site
requires:
    Catalyst:                      5.30
    Log::Log4perl:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
