# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-CDBI-Plain
version:      0.02
version_from: lib/Catalyst/Model/CDBI/Plain.pm
installdirs:  site
requires:
    Catalyst:                      5.00
    Class::DBI:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
