# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-FromForm
version:      0.03
version_from: FromForm.pm
installdirs:  site
requires:
    Class::DBI:                    0
    Data::FormValidator:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
