# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-DBI-SQL-Library
version:      0.14
version_from: lib/Catalyst/Model/DBI/SQL/Library.pm
installdirs:  site
requires:
    Catalyst:                      5.00
    DBI:                           0
    SQL::Library:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
