---
name: Catalyst-Plugin-Upload-MIME
version: 0.01
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Lookup MIME of uploads
license: perl
requires:
  Catalyst: 5.2
  File::MimeInfo: 0
provides:
  Catalyst::Plugin::Upload::MIME:
    file: lib/Catalyst/Plugin/Upload/MIME.pm
    version: 0.01
  Catalyst::Request::Upload:
    file: lib/Catalyst/Plugin/Upload/MIME.pm
    version: 0.01
generated_by: Module::Build version 0.2608
