---
name: Catalyst-View-Petal
version: 0.01
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Petal View Class
license: perl
requires:
  Catalyst: 5
  Petal: 0
provides:
  Catalyst::Helper::View::Petal:
    file: lib/Catalyst/Helper/View/Petal.pm
  Catalyst::View::Petal:
    file: lib/Catalyst/View/Petal.pm
    version: 0.01
generated_by: Module::Build version 0.2609
