# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-SubRequest
version:      0.09
version_from: SubRequest.pm
installdirs:  site
requires:
    Catalyst:                      2.99

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
