use strict;
use Module::Build;

my $build = Module::Build->new(
    create_makefile_pl => 'traditional',
    license            => 'perl',
    module_name        => 'Catalyst::Plugin::Snippets',
    requires           => {
        'perl'     => '5.8.1',
        'Catalyst' => '5.691',
    },
    recommends    => { 'JSON::Syck' },
    create_readme => 1,
    sign          => 1,
);
$build->create_build_script;

