# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-FillInForm
version:      0.06
version_from: FillInForm.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    HTML::FillInForm:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
