# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Authentication-CDBI
version:      0.10
version_from: CDBI.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Catalyst::Model::CDBI:         0
    Catalyst::Plugin::Session::FastMmap: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
