---
name: Catalyst-View-HTML-Template
version: 0.01
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: HTML::Template View Class
license: perl
requires:
  Catalyst: 5
  HTML::Template: 0
provides:
  Catalyst::Helper::View::HTML::Template:
    file: lib/Catalyst/Helper/View/HTML/Template.pm
  Catalyst::View::HTML::Template:
    file: lib/Catalyst/View/HTML/Template.pm
    version: 0.01
generated_by: Module::Build version 0.2609
