---
name: Catalyst-Plugin-Observe
version: 0.02
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Observe Engine Events
license: perl
requires:
  Class::Publisher: 0
provides:
  Catalyst::Plugin::Observe:
    file: lib/Catalyst/Plugin/Observe.pm
    version: 0.02
generated_by: Module::Build version 0.26
