# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-REST-Data-Serializer
version:      0.01
version_from: Serializer.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Data::Serializer:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
