# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-Plucene
version:      0.02
version_from: Plucene.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Plucene::Simple:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
